version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"       # avoid in production if not necessary
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_NAME: todo_db
    volumes:
      - .:/app   # useful in development (hot reload); remove in production

volumes:
  db_data:
