version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"        # remove if not needed on host
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:example@db:3306/todo_db
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: flask run

volumes:
  db_data:
